### ISSUE TITLE
desktop entry file: modify keys Icon and Categories

### ISSUE THREAD

**Issue by sixsixfive** [lxde/compton-conf#25] opened 2016-01-24 15:37 UTC
using the same icon as the window manager settings isn't really intuitive. So i would suggest you use the default icon that comes with compton.

https://github.com/chjj/compton/tree/master/media

-Icon=preferences-system-windows
+Icon=compton

Also for a better Xfce & GNOME integration please add those categories(will display compton in the settings managers)

-Categories=Settings;DesktopSettings;Qt;LXQt;
+Categories=Settings;DesktopSettings;Qt;LXQt;X-XFCE-SettingsDialog;X-XFCE-PersonalSettings;X-GNOME-PersonalSettings;

**Comment by pmattern** [comment] 2016-01-25 18:23
Duplicate of your own bug lxde/lxqt#576. Doesn't make sense.

**Comment by sixsixfive** [comment] 2016-01-25 18:32
When i posted this back then there wasn't a compton icon shipped with compton, but now it is and it should be used since it is more intiutive(eg in lxqt-config overview) than an icon showing two windows(in the most cases)

**Comment by pmattern** [comment] 2016-01-25 19:11
Nobody said your proposal doesn't make sense. Yet the part about the icon is still a duplicate, no matter whether you named a distinct alternate file in the other bug.

But on the other hand I missed your proposal regarding key "Categories" when closing so reopening and editing the title accordingly.

**Closed** 2017-12-08 23:35 UTC
Labels: enhancement
